# ==================================================
# Plugin: UltraDeathMessages
# Author: ShaneDev
# Version: 1.0
# Support Discord: https://discord.gg/T5sR62MnCX
# ==================================================


# The Plugins Prefix in Chat
Prefix: "&f&lUltraDeathMessages &8&l» "

# Victim Placeholder: %victim%
# Killer Placeholder: %killer%


DeathBySword: "&f&lDEATH &8&l» &c%victim% &7was slain by %killer%"
DeathByBow: "&f&lDEATH &8&l» &c%victim% &7was shot to death by %killer%"
DeathBySelf: "&f&lDEATH &8&l» &c%victim% &7Killed themselves."